### ISSUE TITLE
Not working in Visual Studio Community 2022 (64-bit) - Preview

### ISSUE THREAD

**Issue by marbel82** [galtza/RunCommandOnSave#1]
Not working in Microsoft Visual Studio Community 2022 (64-bit) - Version 17.8.0 Preview 2.0.

I try to put .runcommandonsave in the solution directory, and in the project directory, in both cases they don't work, nothing happen.

How can I check if the "Run Command On Save" extension is enabled in my Visual Studio?

**Comment by marbel82** [comment]
Strange thing... it started working today.

I have the .runcommandonsave file in the solution directory.

**Comment by galtza** [comment]
Hi @marbel82,

Great to hear it's functioning correctly. I'm using VS 17.5.4 and haven't run into similar issues, but I'll also test it with your version for completeness.

Concerning the **.runcommandonsave** file, if it's located at /base and your code resides in /base/1/2/3/file.cpp, the extension should find it by traversing up the directory tree.

If you face any more issues, you can activate debug mode by adding the following to your **.runcommandonsave**:

`
[Debug]
On = true
`

With that option, it could produce the following output:

`
C:/base/1/2/3/file.cpp: RunCommandOnSave/PreSave WAS processed

C:/base/1/2/3/file.cpp: RunCommandOnSave/PostSave was NOT processed
`

Best regards,
Galtza
