### ISSUE TITLE
Different command for different extension

### ISSUE THREAD

**Issue by marbel82** [galtza/RunCommandOnSave#2]
Hi,

How can I execute different commands based on file extensions?

I want to run "Format Document" and "Remove Unused Usings" for most files, but for .xaml files, I only want to run "Format Document."

I try:
```ini
[PreSave]
Commands=Edit.FormatDocument
ExcludeExtensions=.xml|.clang-format|.runcommandonsave
[PreSave] (<-- with and without)
Commands=EditorContextMenus.CodeWindow.RemoveAndSort
ExcludeExtensions=.axml|.xml|.clang-format|.runcommandonsave
```

But it doesn't work.

**Comment by galtza** [comment]
Hey there,

Right now, it can only handle one instance of Commands. If you define it a second time, it'll replace the first one.

Great idea, though! I'll work on a design and get back to you soon. 

Ta,
Galtza

**Comment by galtza** [comment]
Hi,

I just submitted a new version that allows you to specify commands per extension. 

`
[PreSave]
Commands=Edit.FormatDocument
ExcludeExtensions=.clang-format|.runcommandonsave

[PreSave.xaml]
Commands=_other_command_
`

Note that ExcludePaths and ExcludeExtensions are only valid on the [PreSave] and [PostSave] (without extension filter).

I hope it helps,
Gatza

**Comment by galtza** [comment]
It was sorted out with version 1.1.0

**Comment by marbel82** [comment]
I thought it would install automatically, but I had to click [Update to 1.1.0]

![image](https://github.com/user-attachments/assets/10482953-fb86-4efc-9cdc-cbbf728175f7)

Visual displayed a message:
_Your changes are scheduled. The modifications will begin when Microsoft Visual Studio is closed._

After restarting I still have version 1.0, and I still have the [Update to 1.1.0] button.

This may be a similar problem I had with the first installation #1, but I don't remember how I fixed it then.

**Comment by marbel82** [comment]
MessageBox appeared under other windows...

After closing Visual Studio, the installation started but showed me:

> VSIX Installer
> This extension is already installed to all applicable products.

**Comment by galtza** [comment]
I need to look into that but in the meanwhile you can uninstall and then install again. Every vsix extension requires to exit all instances of Visual Studio, though.

Alternatively, you can uninstall it and then get the vsix file from the marketplace and install it by double clicking.

Hopefully this will work.

**Comment by marbel82** [comment]
Are you going to fix anything?

Should I wait so we can test it?

If not, I will uninstall and reinstall.

**Comment by galtza** [comment]
Uninstall and install again for now. I cannot commit to a roadmap atm, sorry

**Comment by marbel82** [comment]
After uninstall and install form marketplace (file RunCommandOnSave.vsix 387907B), I still have version 1.0 installed.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/a4e29c84-b159-4a01-892e-ccfb57c2623b">

**Comment by galtza** [comment]
I would try the following:

1. Uninstall (mark to uninstall and close VS to trigger the uninstall) 

2. Make sure it is not installed anymore by opening VS IDE and check in the installed plugins that it is not there

3. Then download the file from the marketplace (not within VS) and double click on it (with VS IDE closed).

Hopefully it works.

I would love to investigate it further but cannot atm

**Comment by marbel82** [comment]
I went through steps 1,2,3 twice before you wrote this.

When I go to the vsix file, the RunCommandOnSave.dll version is 1.0. Maybe that's a clue.

<img width="908" alt="image" src="https://github.com/user-attachments/assets/a78905e8-d196-4802-be54-a9ee7ef991bd">
.

I'll be waiting. Cheers. :)

**Comment by galtza** [comment]
Hi,

I just submitted the version v1.1.1 to GitHub and Marketplace
Hopefully, this time works

Thanks,
Galtza

**Comment by marbel82** [comment]
Success!

After restart VS, the extension did not update automatically, but I install it from marketplace and it installed successfully.

Thanks 👍
